---
- hosts: localhost
  tasks: 
    - name: Simple Task 
      shell: hostname
      notify: trigger1
  handlers: 
    - name: trigger1
      debug: 
        msg: " I am demo handler task trigger by notify action"
